### ISSUE TITLE
looking forward to the R6 branch

### ISSUE THREAD

**Issue by jverzani** [jverzani/gWidgetsWWW2#25]
@jranke -- I'm really looking forward to your work here. Curious what kind of speed improvements come out of it.

**Comment by jranke** [comment]
Thanks, well I am curious as well, that's why I started it of course. However, I was just staring at the source code of R/gwidgets-app.R and R/load.R and I feel less advantageous than yesterday...

In short, from todays perspective, it seems unlikely that I will be able to complete the port...

One example for a question I have relates to the RefClass R_http in R/load.R. Why do you define a new RefClass "Class" in its initialize method? I am not not able to see the reason, maybe because of my lacking knowledge of Rook and http in general...

**Comment by jranke** [comment]
On the positive side, I have a working port of the Array class to R6, and I also ported the ExtArgs class, but have not tested that one.

Also, I changed a lot of comments from ## to # and from ##' to #' which turns out to be rather stupid as now if we compare branches, e.g. via
https://github.com/jverzani/gWidgetsWWW2/compare/R6
we see much more changes than necessary. Which leads me to the question why you chose to use the double hash sign over the single hash at the beginning of the line for normal comments and roxygen comments?

**Comment by jverzani** [comment]
Well, I'm not sure things needed to be done this way, but here are my recollections:

* the Class should be a singleton. I forget why. Likely this can be worked around in a more convenient way. (I only want one http running in R, not one per app)

* The double hash signs is just something I liked and was supported in emacs. There isn't any compelling reason for it.

**Comment by jranke** [comment]
Ah, so maybe we could do away with the Singleton class and just use

tools::startDynamicHelp(start = NA)

from ?startDynamicHelp:

Usage

startDynamicHelp(start = TRUE)

Arguments
start 	

logical: whether to start or shut down the dynamic help system. If NA, the server is started if not already running.

**Comment by jverzani** [comment]
Sounds like a good idea.

On Fri, Oct 9, 2015 at 12:49 PM, Johannes Ranke <notifications@github.com>
wrote:

> Ah, so maybe we could do away with the Singleton class and just use
>
> tools::startDynamicHelp(start = NA)
>
> from ?startDynamicHelp:
>
> Usage
>
> startDynamicHelp(start = TRUE)
>
> Arguments
> start
>
> logical: whether to start or shut down the dynamic help system. If NA, the
> server is started if not already running.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jverzani/gWidgetsWWW2/issues/25#issuecomment-146927918>
> .
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Comment by jranke** [comment]
I think you effectively made the Reference Class `R_http` a singleton by using

```r
R_http <- setRefClass("R_http", ...)$new
```

in its definition, because you did not assign the return value of `setRefClass()` which would be the generator for future instances of Reference Class `R_http`. 

Therefore, when we say 

```
gWidgetsWWW2:::R_http$new()
```

we currently get

```
Error in envRefInferField(x, what, getClass(class(x)), selfEnv) : 
  'new' is not a valid field or method name for reference class "R_http"
```

If this is so, we do in fact not need an extra Reference Class generator `Singleton`, it is enough
to depart from the usual and expected patterns

```r
x <- setRefClass("x", ...)
x <- R6Class("x", ...)
```

and use

```r
x <- setRefClass("x", ...)$new
x <- R6Class("x", ...)$new
```

to make singleton classes. In order to improve the readability, it may be better to say

```r
singleton_x <- setRefClass("x", ...)$new
singleton_x <- R6Class("x", ...)$new
```

What do you think?

**Comment by jverzani** [comment]
If that works. To be honest, it has been so long since I worked this out,
I'm not sure of what I did. Likely you are seeing a much more direct way to
get there.

On Fri, Oct 9, 2015 at 8:58 PM, Johannes Ranke <notifications@github.com>
wrote:

> I think you effectively made the Reference Class R_http a singleton by
> using
>
> R_http <- setRefClass("R_http", ...)$new
>
> in its definition, because you did not assign the return value of
> setRefClass() which would be the generator for future instances of
> Reference Class R_http.
>
> Therefore, when we say
>
> gWidgetsWWW2:::R_http$new()
>
> we currently get
>
> Error in envRefInferField(x, what, getClass(class(x)), selfEnv) :
>   'new' is not a valid field or method name for reference class "R_http"
>
> If this is so, we do in fact not need an extra Reference Class generator
> Singleton, it is enough
> to depart from the usual and expected patterns
>
> x <- setRefClass("x", ...)x <- R6Class("x", ...)
>
> and use
>
> x <- setRefClass("x", ...)$newx <- R6Class("x", ...)$new
>
> to make singleton classes. In order to improve the readability, it may be
> better to say
>
> singleton_x <- setRefClass("x", ...)$newsingleton_x <- R6Class("x", ...)$new
>
> What do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jverzani/gWidgetsWWW2/issues/25#issuecomment-147018537>
> .
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Comment by jranke** [comment]
It does work indeed, at least browse_df() and my gmkin application. If you 
check out the current R6 branch, you can check...

I have ported a couple of reference classes to R6 so far. At the moment, 
I am working on the GCompound class. WhenI have completed that, I will 
have to port all of the derived classes for them to work again. Still not 
sure if I will get there, due to other duties. And then it probably will not 
work at first, so it may be that I will want to ask your for help in getting 
the bugs out...

At the moment, I am asking myself about `coerce_with`. There are 
functions
operating on this field, in GComponent, but the field is only defined in the 
derived class GWidget. Should I move the field definition to GComponent?

The other class derived from GWidget is GContainer, and this does not 
have the coerce_with field. So maybe I should move the functions using 
coerce_with to GWidget? Does that make more sense?

**Comment by jverzani** [comment]
Excellent. I'll have to check it out when I get a chance. The `coerce_with`
field is only needed for widgets for which it may be desirable for `svalue`
to return something other than a string. These were only "widgets", hence
it sits there. It could be higher up -- it doesn't really hurt anything.
The only place it comes in -- if I recall -- is in a definition like
`get_value=function() coerce_with(value)`.

On Sun, Oct 11, 2015 at 9:17 AM, Johannes Ranke <notifications@github.com>
wrote:

> It does work indeed, at least browse_df() and my gmkin application. If you
> check out the current R6 branch, you can check...
>
> I have ported a couple of reference classes to R6 so far. At the moment,
> I am working on the GCompound class. WhenI have completed that, I will
> have to port all of the derived classes for them to work again. Still not
> sure if I will get there, due to other duties. And then it probably will
> not
> work at first, so it may be that I will want to ask your for help in
> getting
> the bugs out...
>
> At the moment, I am asking myself about `coerce_with`. There are
> functions
> operating on this field, in GComponent, but the field is only defined in
> the
> derived class GWidget. Should I move the field definition to GComponent?
>
> The other class derived from GWidget is GContainer, and this does not
> have the coerce_with field. So maybe I should move the functions using
> coerce_with to GWidget? Does that make more sense?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jverzani/gWidgetsWWW2/issues/25#issuecomment-147191846>
> .
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Comment by jranke** [comment]
Currently I am confused about the toplevel object: is it possible to have more than one toplevel object in one R session? I thought this is not possible, as currently it lives as .gWidgets_toplevel in the global environment? Could we make toplevel a field in the gWidgetsWWW2:::r_httpd instance of R_http?

Also, could we make the session manager a field of r_httpd, so it would be available to all apps loaded within an R session? Or do you imagine a scenario where we would need more than one session manager?

**Comment by jverzani** [comment]
If I recall correctly, there is one toplevel instance per "app." This was a
way to find the object from within the main workspace. Maybe keeping an
environment keyed by a uuid would be a better thing. As for session
manager, I think that could be streamlined. Glancing over the code it seems
to be handling the case of rapache and rook. Are you planning on deploying
these apps or running locally? If the former, isn't there some newer
node-based stuff for web programming in R? (I haven't kept up.) If so, you
might want to look there, rather than RApache.

On Mon, Oct 12, 2015 at 2:24 AM, Johannes Ranke <notifications@github.com>
wrote:

> Currently I am confused about the toplevel object: is it possible to have
> more than one toplevel object in one R session? I thought this is not
> possible, as currently it lives as .gWidgets_toplevel in the global
> environment? Could we make toplevel a field in the gWidgetsWWW2:::r_httpd
> instance of R_http?
>
> Also, could we make the session manager a field of r_httpd, so it would be
> available to all apps loaded within an R session? Or do you imagine a
> scenario where we would need more than one session manager?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jverzani/gWidgetsWWW2/issues/25#issuecomment-147299637>
> .
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Comment by jranke** [comment]
Yes, the code looks as if it was the intention to 
have one toplevel per app. But wouldn't it be 
enough if we had one session per app and 
only one toplevel object per R session?

I am only looking at local apps via Rook at the 
moment. Exposing R via the web would require 
too many safety considerations that I do not 
feel I am up to.

**Comment by jranke** [comment]
OK, my comment was maybe not too intelligent... For the moment, I will stick to the way toplevel objects and session managers are handled.... The setup of the whole package is really impressive, the more I dig into it... I think if the performance were better for complex GUIs this would still be a great alternative to shiny, because of the more complex GUI elements that are possible with little coding.

Anyway, I just pushed to the R6 branch. The current state has GComponent and GWidget ported to R6, but only very few widgets are available. The branch can be built using --no-build-vignettes and then installed (or using make install-no-vignettes). I tried browse_df() but the page does not load.

@jverzani As things are fairly complex, I would appreciate if you could have a look why browse_df() does not work as expected...

**Comment by jverzani** [comment]
I'll give it a go. My first attempt at displaying a window is hanging
though, so I'll have to sort out what is going on there first.

On Wed, Oct 14, 2015 at 2:13 AM, Johannes Ranke <notifications@github.com>
wrote:

> OK, my comment was maybe not too intelligent... For the moment, I will
> stick to the way toplevel objects and session managers are handled.... The
> setup of the whole package is really impressive, the more I dig into it...
> I think if the performance were better for complex GUIs this would still be
> a great alternative to shiny, because of the more complex GUI elements that
> are possible with little coding.
>
> Anyway, I just pushed to the R6 branch. The current state has GComponent
> and GWidget ported to R6, but only very few widgets are available. The
> branch can be built using --no-build-vignettes and then installed (or using
> make install-no-vignettes). I tried browse_df() but the page does not load.
>
> @jverzani <https://github.com/jverzani> As things are fairly complex, I
> would appreciate if you could have a look why browse_df() does not work as
> expected...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jverzani/gWidgetsWWW2/issues/25#issuecomment-147947786>
> .
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Comment by jranke** [comment]
Great! I hope it is just one or two little porting errors (not always easy to 
figure out what exactly needs to be done to make it work with R6)...


I'll give it a go. My first attempt at displaying a window is hangingthough, so 
I'll have to sort out what is going on there first.

On Wed, Oct 14, 2015 at 2:13 AM, Johannes Ranke 
<notifications@github.com>wrote:

> OK, my comment was maybe not too intelligent... For the moment, I will> 
stick to the way toplevel objects and session managers are handled.... 
The> setup of the whole package is really impressive, the more I dig into 
it...> I think if the performance were better for complex GUIs this would still 
be> a great alternative to shiny, because of the more complex GUI 
elements that> are possible with little coding.>> Anyway, I just pushed to 
the R6 branch. The current state has GComponent> and GWidget ported 
to R6, but only very few widgets are available. The> branch can be built 
using --no-build-vignettes and then installed (or using> make install-no-
vignettes). I tried browse_df() but the page does not load.>> @jverzani 
<https://github.com/jverzani> As things are fairly complex, I> would 
appreciate if you could have a look why browse_df() does not work as> 
expected...>> —> Reply to this email directly or view it on GitHub> 
<https://github.com/jverzani/gWidgetsWWW2/issues/25#issuecomment-147
947786>> .>



-- John VerzaniChair, Department of MathematicsCollege of Staten Island, 
CUNYverzani@math.csi.cuny.edu


—Reply to this email directly or view it on GitHub[1].[2]



-- 
PD Dr. Johannes Ranke
Kronacher Str. 8
79639 Grenzach-Wyhlen

--------
[1] 
https://github.com/jverzani/gWidgetsWWW2/issues/25#issuecomment-1480
27151
[2] 
https://github.com/notifications/beacon/ADdArUDRm9KgLlxw0b-9P92W4yYjUj
Ciks5o7jnsgaJpZM4GLr22.gif

**Comment by jranke** [comment]
I discovered that I can find porting bugs by generating widgets directly, without load_app. So I just pushed a couple of fixes to the R6 branch and ported glabel to allow for a minimal testing setup. Sorry, should have done that right away. However, still now widgets appear in the window when I load a minimal test app or use browse_df(). I will have to find a different debugging strategy for that...

**Comment by jverzani** [comment]
I still can't get load_app to load an app. It just hangs. Shouldn't a
script like this work:

w = gwindow("test")
l = glabel("hello world", cont=w)

As well, what actually causes the javascript for w to print out? (So I can
debug a bit from the command line.)  I know it isn't show, and have totally
forgotten what it should be

On Sat, Oct 17, 2015 at 3:14 AM, Johannes Ranke <notifications@github.com>
wrote:

> I discovered that I can find porting bugs by generating widgets directly,
> without load_app. So I just pushed a couple of fixes to the R6 branch and
> ported glabel to allow for a minimal testing setup. Sorry, should have done
> that right away. However, still now widgets appear in the window when I
> load a minimal test app or use browse_df(). I will have to find a different
> debugging strategy for that...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jverzani/gWidgetsWWW2/issues/25#issuecomment-148892495>
> .
>



-- 
John Verzani
Chair, Department of Mathematics
College of Staten Island, CUNY
verzani@math.csi.cuny.edu

**Comment by jranke** [comment]
Good question - in my case load_app does not complain in the R console, and the title of the browser window is set, but no widget is shown. And I have exactly this problem that I do not know how to find the problem...
